---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install apt packages
    package:
      name:
        - git
        - ansible
        - python3-pip

  - name: install pip packages
    pip:
      name:
        - psutil

  - name: install snaps
    community.general.snap:
      name:
        - brave

  # Install a snap with classic confinement
  - name: install vscode with option --classic
    community.general.snap:
      name: code
      classic: yes
        
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: wouter
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: wouter
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: set favorites
    become_user: wouter
    dconf:
      key: "/org/gnome/shell/favorite-apps"
      value: "['org.gnome.Nautilus.desktop', 'snap-store_ubuntu-software.desktop', 'brave_brave.desktop', 'code_code.desktop', 'org.gnome.Terminal.desktop']"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/wouter/.bashrc
      owner: wouter
      group: wouter

  - name: copy .gitconfig file
    copy:
      src: files/gitconfig
      dest: /home/wouter/.gitconfig
      owner: wouter
      group: wouter

  - name: add ansible user
    user:
      name: ansible
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/WouterSpaans/ansible.git
